version: '3.3'

services:
    nginx:
      container_name: nginx
      image: magicwebs5770/mw-images:nginx-test
      restart: always
      ports:
          - 80:80
          - 443:443
      volumes:
          - /home/magicwebs/webinar-test/logs/nginx:/var/log/nginx
          - /home/magicwebs/webinar-test/conf/nginx:/etc/nginx/conf.d
          - /home/magicwebs/webinar-test/www:/var/www
      links:
          - fpm
    fpm:
      image: magicwebs5770/mw-images:fpm-test
      restart: always
      volumes:
          - /home/magicwebs/webinar-test/www:/var/www
      links:
          - mysql
    mysql:
      container_name: mysql
      image: mysql:5.7
      restart: always
      volumes:
          - /home/magicwebs/webinar-test/images/mysql:/root
      ports:
          - 3306:3306
      environment:
          - MYSQL_ROOT_PASSWORD=123qweASD
          - MYSQL_DATABASE=webinar
